#!/usr/bin/env python3
"""Give every benchmark registered inputs and outputs.

WHY. reg2reg timing is the right metric -- it excludes the reset trees and I/O buffers
that were otherwise dominating the critical path -- but it is only COMPLETE if all the
logic actually sits between registers. 13 benchmarks had their real work hanging off an
unregistered input, so their all-paths critical path began at a data port (r11 at
din[31], -2.722 ns) while reg2reg reported positive slack and saw none of it.

That produced a false finding: "retiming is harmful on 10 of 25 benchmarks", with
r01-r03 at 600-785x worse. In truth the original hid its logic on an input path that
reg2reg cannot see, and when the tool retimed it distributed registers INTO that logic,
creating real reg2reg paths -- so the metric punished the tool for making the work
visible. The tool was behaving correctly.

HOW. The module is renamed to <top>_core and a new <top> wrapper is generated with the
same ports, registering every input before the core and every output after it. Applied
identically to orig, retimed and directive, so the variants stay equivalent to each
other -- which is what the equivalence checks compare. Latency grows by 2 cycles for
every variant equally.

clk and rst_n pass through unregistered: registering a clock is meaningless and
registering the reset would change reset semantics.
"""

from pathlib import Path
import sys

import argparse
import re

ROOT = Path(__file__).resolve().parent.parent
PORT_RE = re.compile(r"\b(input|output)\s+(?:wire|logic|reg)?\s*(?:\[([^\]]+)\]\s*)?(\w+)")

MAX_PORT_W = 32

MAX_TOTAL_PINS = 120

SER_W = 8

def width_of(w):
    """Bit width from a [msb:lsb] string, or 1 for a scalar. None if not a literal."""
    if not w:
        return 1
    m = re.match(r"^\s*(\d+)\s*:\s*(\d+)\s*$", w)
    return int(m.group(1)) - int(m.group(2)) + 1 if m else None

def ports(src, top):
    m = re.search(rf"\bmodule\s+{re.escape(top)}\b", src)
    head = src[m.end():]
    head = head[:head.index(");")]
    return [(g.group(1), g.group(2), g.group(3)) for g in PORT_RE.finditer(head)]

SENTINEL = "// RT_WRAPPER_BEGIN -- generated by commands/add_registered_io_wrapper.py"

def wrap(src, top):
    if f"module {top}_core" in src:
        i = src.find(SENTINEL)
        if i < 0:
            j = src.find("// Registered-I/O wrapper generated by")
            if j < 0:
                return None
            i = src.rfind("// ---", 0, j)
            if i < 0:
                i = j
        src = src[:i].rstrip() + "\n"
        src = re.sub(rf"\bmodule\s+{re.escape(top)}_core\b",
                     f"module {top}", src, count=1)
    pl = ports(src, top)
    ins = [(w, n) for d, w, n in pl if d == "input" and n not in ("clk", "rst_n")]
    has_rst = any(n == "rst_n" for _, _, n in pl)

    outs = [(w, n) for d, w, n in pl if d == "output"]
    if not ins or not outs:
        return None
    def budget(cap):
        tot = 1 + (1 if has_rst else 0)
        for w, n in ins + outs:
            ww = width_of(w) or 1
            tot += min(ww, cap)
        return tot

    cap = 1 << 30                       # no narrowing at all
    if budget(cap) > MAX_TOTAL_PINS:
        cap = MAX_PORT_W
        while cap > 4 and budget(cap) > MAX_TOTAL_PINS:
            cap //= 2
    narrow_in = {n: width_of(w) for w, n in ins
                 if width_of(w) and width_of(w) > cap}
    narrow_out = {n: width_of(w) for w, n in outs
                  if width_of(w) and width_of(w) > cap}

    KEEP = ('(* dont_touch = "yes", RETIMING_FORWARD = 0, RETIMING_BACKWARD = 0 *)')

    def decl(w, n, sfx=""):
        return f"  {KEEP}\n  logic {f'[{w}] ' if w else ''}{n}{sfx};"

    body = [SENTINEL,
            f"// ---------------------------------------------------------------------",
            f"// Every input is captured and every output is registered, so ALL logic in",
            f"// {top}_core lies between flip-flops and reg2reg timing sees all of it.",
            f"// Applied identically to every variant, so the variants remain equivalent",
            f"// to one another; each simply gains the same 2 cycles of latency.",
            f"// ---------------------------------------------------------------------",
            f"module {top} ("]
    plist = ["    input  logic clk,"]
    if has_rst:
        plist.append("    input  logic rst_n,")
    for w, n in ins:
        ww = f"[{SER_W-1}:0] " if n in narrow_in else (f"[{w}] " if w else "")
        plist.append(f"    input  logic {ww}{n},")
    for i, (w, n) in enumerate(outs):
        comma = "," if i < len(outs) - 1 else ""
        ww = f"[{SER_W-1}:0] " if n in narrow_out else (f"[{w}] " if w else "")
        plist.append(f"    output logic {ww}{n}{comma}")
    body += plist + [");"]
    init = "" if has_rst else " = '0"
    body += [decl(f"{SER_W-1}:0" if n in narrow_in else w, n, f"_iq{init}")
             for w, n in ins]
    body += [decl(w, n, "_c") for w, n in outs]
    for w, n in ins:
        if n in narrow_in:
            W = narrow_in[n]
            k = max(1, W // SER_W)
            cw = max(1, (k - 1).bit_length())
            body += [f"  logic [{W-1}:0] {n}_sr, {n}_word;",
                     f"  logic [{cw-1}:0] {n}_cnt;",
                     "  always_ff @(posedge clk) begin"]
            if has_rst:
                body += [f"    if (!rst_n) begin",
                         f"      {n}_sr <= '0; {n}_word <= '0; {n}_cnt <= '0;",
                         f"    end else begin"]
            else:
                body += ["    begin"]
            body += [f"      {n}_sr  <= {{{n}_sr[{W-SER_W-1}:0], {n}_iq}};",
                     f"      {n}_cnt <= ({n}_cnt == {k-1}) ? '0 : {n}_cnt + 1'b1;",
                     f"      // word complete on the last beat: latch it, hold it stable",
                     f"      if ({n}_cnt == {k-1})",
                     f"        {n}_word <= {{{n}_sr[{W-SER_W-1}:0], {n}_iq}};",
                     "    end", "  end"]
    for w, n in outs:
        if n in narrow_out:
            W = narrow_out[n]
            k = max(1, W // SER_W)
            body += [f"  logic [{W-1}:0] {n}_sr;",
                     f"  logic [{max(1, (k-1).bit_length())-1}:0] {n}_cnt;",
                     "  always_ff @(posedge clk) begin"]
            g = "    " if not has_rst else "    else "
            if has_rst:
                body += [f"    if (!rst_n) begin {n}_sr <= '0; {n}_cnt <= '0; end"]
            body += [f"{g}begin",
                     f"      {n}_cnt <= ({n}_cnt == {k-1}) ? '0 : {n}_cnt + 1'b1;",
                     f"      {n}_sr  <= ({n}_cnt == 0) ? {n}_c"
                     f" : {{{n}_sr[{W-SER_W-1}:0], {SER_W}'h0}};",
                     "    end", "  end"]
    body += ["", "  // capture inputs", "  always_ff @(posedge clk) begin"]
    if has_rst:
        body += ["    if (!rst_n) begin"]
        body += [f"      {n}_iq <= '0;" for w, n in ins]
        body += ["    end else begin"]
        body += [f"      {n}_iq <= {n};" for w, n in ins]
        body += ["    end"]
    else:
        body += [f"    {n}_iq <= {n};" for w, n in ins]
    body += ["  end", "",
             f"  {top}_core u_core (",
             "    .clk(clk), .rst_n(rst_n)," if has_rst else "    .clk(clk),"]
    body += [f"    .{n}({n}_word)," if n in narrow_in else f"    .{n}({n}_iq),"
             for w, n in ins]
    body += [f"    .{n}({n}_c)," for w, n in outs[:-1]]
    body += [f"    .{outs[-1][1]}({outs[-1][1]}_c)", "  );", "",
             "  // register outputs", "  always_ff @(posedge clk) begin"]
    if has_rst:
        body += ["    if (!rst_n) begin"]
        body += [f"      {n} <= '0;" for w, n in outs]
        body += ["    end else begin"]
        body += [f"      {n} <= {n}_sr[{narrow_out[n]-1}:{narrow_out[n]-SER_W}];"
                 if n in narrow_out else f"      {n} <= {n}_c;" for w, n in outs]
        body += ["    end"]
    else:
        body += [f"    {n} <= {n}_sr[{narrow_out[n]-1}:{narrow_out[n]-SER_W}];"
                 if n in narrow_out else f"    {n} <= {n}_c;" for w, n in outs]
    body += ["  end", "", "endmodule"]

    core = re.sub(rf"\bmodule\s+{re.escape(top)}\b", f"module {top}_core", src, count=1)
    core = re.sub(rf"^endmodule\s*$", "endmodule", core, count=0, flags=re.M)
    return core.rstrip() + "\n\n" + "\n".join(body) + "\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default=None)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    want = set(args.only.split(",")) if args.only else None
    n = 0
    for bd in sorted((ROOT / "benchmarks").iterdir()):
        if not (bd / "variants" / "orig").is_dir():
            continue
        if want and bd.name not in want:
            continue
        top = None
        for line in (bd / "bench.yaml").read_text().splitlines():
            if line.startswith("top:"):
                top = line.split(":", 1)[1].strip()
        for vd in sorted((bd / "variants").iterdir()):
            for f in sorted(vd.glob("*.sv")):
                src = f.read_text()
                if f"module {top}\b" not in src and not re.search(
                        rf"\bmodule\s+{re.escape(top)}\b", src):
                    continue
                new = wrap(src, top)
                if new is None:
                    continue
                print(f"  {'would wrap' if args.dry_run else 'wrapped'} {f}")
                if not args.dry_run:
                    f.write_text(new)
                n += 1
    print(f"{n} file(s)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
