#!/usr/bin/env python3
"""Generate a uniform testbench for a benchmark top module.

The same testbench serves three purposes:
  1. deterministic stimulus, so orig/retimed traces are directly comparable
  2. a per-cycle output trace, which is how we check strict-retiming equivalence
  3. a VCD, which is how we get switching activity for power

It deliberately re-asserts reset partway through the run.  A retimed design with
a wrong new reset value passes a reset-once test and fails this one, and getting
the reset value right is the whole point of the Class A benchmarks.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from benchmark_lib.systemverilog_module import parse_module

import argparse

RESET_NAMES = {"rst_n": 0, "resetn": 0, "reset_n": 0, "arst_n": 0,
               "rst": 1, "reset": 1, "arst": 1}

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("--top", default=None)
    ap.add_argument("--out", required=True)
    ap.add_argument("--cycles", type=int, default=2000)
    args = ap.parse_args()

    top, ports = parse_module(args.source, args.top)

    clk = next((p["name"] for p in ports if p["name"] in ("clk", "clock")), None)
    if clk is None:
        raise SystemExit(f"gen_tb: {top} has no clk/clock port")

    rst, rst_active_high = None, None
    for p in ports:
        if p["name"] in RESET_NAMES:
            rst, rst_active_high = p["name"], bool(RESET_NAMES[p["name"]])
            break

    driven = [p for p in ports if p["dir"] == "input"
              and p["name"] not in (clk, rst)]
    outs = [p for p in ports if p["dir"] == "output"]

    L = []
    a = L.append
    a("// AUTO-GENERATED by commands/generate_testbench.py -- do not edit by hand.")
    a(f"// Testbench for {top}")
    a("`timescale 1ns/1ps")
    a("")
    a(f"module tb_{top};")
    a("")
    a("  // ---- plusargs ----")
    a("  integer  trace_fd = 0;")
    a("  string   trace_path;")
    a("  string   vcd_path;")
    a(f"  integer  n_cycles = {args.cycles};")
    a("")
    a("  logic clk = 1'b0;")
    if rst:
        a(f"  logic {rst};")
    for p in driven:
        w = "" if p["width"] == 1 else f"[{p['msb']}:{p['lsb']}] "
        a(f"  logic {w}{p['name']};")
    for p in outs:
        w = "" if p["width"] == 1 else f"[{p['msb']}:{p['lsb']}] "
        a(f"  logic {w}{p['name']};")
    a("")
    a("  // 1 GHz nominal in TB units; the real period comes from the SDC/XDC.")
    a("  always #0.5 clk = ~clk;")
    a("")
    a("  // ---- deterministic stimulus: 64-bit xorshift, no $random ----")
    a("  logic [63:0] lfsr = 64'h0123_4567_89AB_CDEF;")
    a("  function automatic logic [63:0] nxt(input logic [63:0] s);")
    a("    logic [63:0] x;")
    a("    x = s;")
    a("    x = x ^ (x << 13);")
    a("    x = x ^ (x >> 7);")
    a("    x = x ^ (x << 17);")
    a("    nxt = x;")
    a("  endfunction")
    a("")
    a(f"  {top} dut (")
    conn = [f"    .{clk}(clk)"]
    if rst:
        conn.append(f"    .{rst}({rst})")
    for p in driven + outs:
        conn.append(f"    .{p['name']}({p['name']})")
    a(",\n".join(conn))
    a("  );")
    a("")
    a("  integer cyc = 0;")
    a("")
    a("  initial begin")
    a('    if ($value$plusargs("trace=%s", trace_path)) begin')
    a('      trace_fd = $fopen(trace_path, "w");')
    a("    end")
    a('    if ($value$plusargs("vcd=%s", vcd_path)) begin')
    a("      $dumpfile(vcd_path);")
    a(f"      $dumpvars(0, tb_{top});")
    a("    end")
    a('    void\'($value$plusargs("cycles=%d", n_cycles));')
    a("  end")
    a("")
    a("  // ---- drive ----")
    a("  initial begin")
    if rst:
        a(f"    {rst} = {'1' if rst_active_high else '0'};   // asserted")
    for p in driven:
        a(f"    {p['name']} = '0;")
    a("    repeat (6) @(posedge clk);")
    if rst:
        a(f"    {rst} = {'0' if rst_active_high else '1'};   // released")
    a("  end")
    a("")
    a("  // Second reset pulse partway through: this is what catches a bad")
    a("  // retimed reset value.")
    if rst:
        a("  initial begin")
        a("    @(negedge clk);")
        a("    repeat (n_cycles/2) @(posedge clk);")
        a(f"    {rst} = {'1' if rst_active_high else '0'};")
        a("    repeat (4) @(posedge clk);")
        a(f"    {rst} = {'0' if rst_active_high else '1'};")
        a("  end")
        a("")
    for i, p in enumerate(driven):
        w = p["width"]
        if w <= 64:
            continue
        n = (w + 63) // 64
        parts = []
        for j in range(n):
            r = (j * 13 + 5) % 64
            k = (0x9E3779B97F4A7C15 * (j + 1)) & 0xFFFFFFFFFFFFFFFF
            parts.append(f"(((lfsr << {r}) | (lfsr >> {64 - r})) ^ 64'h{k:016X})")
        a(f"  wire [{n * 64 - 1}:0] {p['name']}_wide =")
        a("      {" + (",\n       ".join(parts)) + "};")
    a("")
    a("  always @(posedge clk) begin")
    a("    lfsr <= nxt(lfsr);")
    for i, p in enumerate(driven):
        if p["width"] == 1:
            a(f"    {p['name']} <= lfsr[{(i * 7) % 64}];")
        else:
            w = p["width"]
            if w <= 64:
                span = max(1, 64 - w + 1)
                off = (i * 13 + 3) % span
                a(f"    {p['name']} <= lfsr[{off} +: {w}];")
            else:
                a(f"    {p['name']} <= {p['name']}_wide[{w - 1}:0];")
    a("  end")
    a("")
    a("  // ---- trace + finish ----")
    a("  always @(posedge clk) begin")
    a("    cyc <= cyc + 1;")
    a("    if (trace_fd != 0) begin")
    fmt = " ".join("%h" for _ in outs)
    argl = ", ".join(p["name"] for p in outs)
    if rst:
        a(f'      $fwrite(trace_fd, "%0d %b {fmt}\\n", cyc, {rst}, {argl});')
    else:
        a(f'      $fwrite(trace_fd, "%0d - {fmt}\\n", cyc, {argl});')
    a("    end")
    a("    if (cyc >= n_cycles) begin")
    a("      if (trace_fd != 0) $fclose(trace_fd);")
    a("      $finish;")
    a("    end")
    a("  end")
    a("")
    a("endmodule")

    Path(args.out).write_text("\n".join(L) + "\n")
    print(f"gen_tb: wrote {args.out} for {top} "
          f"({len(driven)} driven inputs, {len(outs)} outputs)")

if __name__ == "__main__":
    main()
