#!/usr/bin/env python3
"""Prove two variants equivalent, instead of testing them on 4000 cycles.

Bounded simulation is what the suite has used so far, and it is not enough.  Today it
reported PASS on r28 and r29 while commands/generate_testbench.py was driving a 512-bit port from a
64-bit LFSR -- 448 bits held constant, three quarters of the input space never
exercised.  Nothing was actually broken, but a PASS under those conditions carries far
less information than it appeared to.

Conformal's retiming-aware modes need Conformal_Ultra and the site has Conformal_Asic,
so this uses yosys + sby, which are installed locally.  Note eqy is the wrong tool
here: it partitions on matching flops, and a retimed pair deliberately has different
registers.  A miter proved by k-induction does not care where the registers are.

Runs on donut rather than eq1: no license needed, and it leaves the shared box for
synthesis and place-and-route.
"""

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from benchmark_lib.benchmark import Benchmark

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import argparse
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent
SBY = Path.home() / ".local/bin/sby"

PORT_RE = re.compile(
    r"\b(input|output)\s+(?:wire|logic|reg)?\s*(?:\[([^\]]+)\]\s*)?(\w+)")

def load_meta(benchmark_directory):
    return Benchmark(benchmark_directory).fields

def ports(src, top):
    """(dir, width_expr_or_None, name) for the module header only.

    Anchored on `module <top>` rather than the first "(" in the file: these sources
    open with a long comment block, and slicing from the first parenthesis pulled
    words out of the prose (it reported a port named "toggles").
    """
    m = re.search(rf"\bmodule\s+{re.escape(top)}\b", src)
    head = src[m.end():]
    head = head[:head.index(");")]
    return [(g.group(1), g.group(2), g.group(3)) for g in PORT_RE.finditer(head)]

def wrapper(top, ports_, settle, skew=0):
    """A miter with an explicit RESET PROTOCOL.

    yosys's `miter -equiv` compares the two designs from their inferred init values,
    with no reset applied -- so it failed at step 0 on r20, which is not a bug in the
    RTL but a comparison made before either design was initialised.  A retimed variant
    has registers the original does not, and their init values have no reason to match
    until reset has run.

    So: hold rst_n low for `settle` cycles, then release it, and only assert output
    equality after that.  This is the same protocol commands/check_equivalence_by_simulation.py uses in
    simulation, which is why simulation never saw a step-0 mismatch.
    """
    ins = [(w, n) for d, w, n in ports_ if d == "input" and n not in ("clk", "rst_n")]
    outs = [(w, n) for d, w, n in ports_ if d == "output"]
    decl = "".join(f"  input {f'[{w}] ' if w else ''}{n},\n" for w, n in ins)
    conn = "".join(f"    .{n}({n}),\n" for w, n in ins)
    gold_o = "".join(f"  wire {f'[{w}] ' if w else ''}{n}_gold;\n" for w, n in outs)
    gate_o = "".join(f"  wire {f'[{w}] ' if w else ''}{n}_gate;\n" for w, n in outs)
    cg = "".join(f"    .{n}({n}_gold),\n" for w, n in outs)
    ck = "".join(f"    .{n}({n}_gate),\n" for w, n in outs)
    eqs = " && ".join(f"({n}_gold == {n}_gate)" for w, n in outs)
    if skew:
        regs, eqs_parts = [], []
        for w, n in outs:
            wd = f"[{w}] " if w else ""
            regs.append(f"  logic {wd}{n}_gold_d [{skew}];")
            regs.append(f"  always_ff @(posedge clk) begin")
            regs.append(f"    {n}_gold_d[0] <= {n}_gold;")
            for k in range(1, skew):
                regs.append(f"    {n}_gold_d[{k}] <= {n}_gold_d[{k-1}];")
            regs.append(f"  end")
            eqs_parts.append(f"({n}_gold_d[{skew-1}] == {n}_gate)")
        skew_regs = "\n".join(regs)
        eqs_skewed = " && ".join(eqs_parts)
    else:
        skew_regs = ""
        eqs_skewed = eqs
    return f"""// Generated by commands/prove_equivalence_formally.py -- miter with a reset protocol.
module fm_miter (
  input clk,
{decl}  output logic ok
);
  logic [7:0] cyc = 8'd0;
  always_ff @(posedge clk) if (cyc != 8'hFF) cyc <= cyc + 8'd1;

  // reset asserted (active low) for the first {settle} cycles, then released
  wire rst_n = (cyc >= 8'd{settle});

{gold_o}{gate_o}
  {top} gold (.clk(clk), .rst_n(rst_n),
{conn}{cg[:-2]}
  );
  {top}__gate gate (.clk(clk), .rst_n(rst_n),
{conn}{ck[:-2]}
  );

{skew_regs}
  assign ok = {eqs_skewed};

  // Compare only once reset has been released and both designs have settled.
  always_ff @(posedge clk)
    if (cyc > 8'd{settle + 1}) assert (ok);

endmodule
"""

def sby_text(top, work, depth, mode):
    return f"""[options]
mode {mode}
depth {depth}

[engines]
smtbmc z3

[script]
read_verilog -sv gold.sv
read_verilog -sv gate.sv
read_verilog -sv fm_miter.sv
prep -top fm_miter -flatten

[files]
{work}/gold.sv
{work}/gate.sv
{work}/fm_miter.sv
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("bench")
    ap.add_argument("--a", default="orig")
    ap.add_argument("--b", default="retimed")
    ap.add_argument("--depth", type=int, default=12)
    ap.add_argument("--mode", default="prove", choices=["prove", "bmc"])
    ap.add_argument("--timeout", type=int, default=900)
    ap.add_argument("--skew", type=int, default=0,
                    help="cycles the reference adds; delays gold before comparing")
    ap.add_argument("--settle", type=int, default=3,
                    help="cycles to hold reset before comparing outputs")
    args = ap.parse_args()

    bdir = ROOT / "benchmarks" / args.bench
    top = None
    meta = subprocess.run([sys.executable, str(ROOT / "commands" / "read_benchmark_field.py"),
                           str(bdir)], capture_output=True, text=True).stdout
    for line in meta.splitlines():
        if line.startswith("top="):
            top = line.split("=", 1)[1]
    gold = sorted((bdir / "variants" / args.a).glob("*.sv"))[0]
    gate = sorted((bdir / "variants" / args.b).glob("*.sv"))[0]

    name = f"formal_{args.bench}_{args.a}_vs_{args.b}"
    work = ROOT / "build" / "formal_src" / name
    work.mkdir(parents=True, exist_ok=True)
    gsrc = gold.read_text()
    (work / "gold.sv").write_text(gsrc)
    (work / "gate.sv").write_text(
        re.sub(rf"\b{re.escape(top)}\b", f"{top}__gate", gate.read_text()))
    pl = ports(gsrc, top)
    (work / "fm_miter.sv").write_text(
        wrapper(top, pl, args.settle, args.skew))
    sf = ROOT / "build" / f"{name}.sby"
    sf.write_text(sby_text(top, work, args.depth, args.mode))

    r = subprocess.run([str(SBY), "-f", str(sf)], capture_output=True, text=True,
                       timeout=args.timeout, cwd=str(ROOT))
    out = r.stdout + r.stderr
    verdict = "UNKNOWN"
    for line in out.splitlines():
        if "PASS" in line and "DONE" in line:
            verdict = "PROVED" if args.mode == "prove" else f"BMC-{args.depth} clean"
        elif "FAIL" in line and "DONE" in line:
            verdict = "COUNTEREXAMPLE"
    print(f"  {args.bench:<32}{args.a} vs {args.b}: {verdict}")
    if verdict == "UNKNOWN":
        for line in out.splitlines()[-12:]:
            print(f"      {line}")
    return 0 if verdict.startswith(("PROVED", "BMC")) else 1

if __name__ == "__main__":
    raise SystemExit(main())
